Repository mapsforge/mapsforge, pull requests merged in 2023-07, with the labels that each got.

#1426 POI: optimize, fix multiple patterns
  mapsforge-poi-android/src/main/java/org/mapsforge/poi/android/storage/AndroidPoiPersistenceManager.java
  mapsforge-poi-awt/src/main/java/org/mapsforge/poi/awt/storage/AwtPoiPersistenceManager.java
  mapsforge-poi-writer/src/main/config/poi-mapping.xml
  mapsforge-poi/src/main/java/org/mapsforge/poi/storage/AbstractPoiPersistenceManager.java
  mapsforge-poi/src/main/java/org/mapsforge/poi/storage/DbConstants.java
  mapsforge-poi/src/main/java/org/mapsforge/poi/storage/PoiCategoryRangeQueryGenerator.java
  mapsforge-poi/src/main/java/org/mapsforge/poi/storage/PoiPersistenceManager.java
  mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/PoiSearchViewer.java
Labels: enhancement, poi

#1427 MapFileWriter: increase poi data buffer size
  mapsforge-map-writer/src/main/java/org/mapsforge/map/writer/MapFileWriter.java
Labels: bug

#1432 Polygon: enable handling of holes
  mapsforge-map/src/main/java/org/mapsforge/map/layer/overlay/Polygon.java
  mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/OverlayMapViewer.java
Labels: enhancement
